CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS ${UNIVERSITIES_TABLE} (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  country VARCHAR(100),
  url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ${DEGREE_PROGRAMS_TABLE} (
  id SERIAL PRIMARY KEY,
  university_id INTEGER NOT NULL REFERENCES ${UNIVERSITIES_TABLE}(id) ON DELETE CASCADE,
  program_name VARCHAR(500) NOT NULL,
  course_type VARCHAR(100),
  is_online BOOLEAN DEFAULT FALSE,
  source_url TEXT,
  last_seen TIMESTAMP,
  quality_flag VARCHAR(50) DEFAULT 'low',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ${TUITION_PATTERNS_TABLE} (
  id SERIAL PRIMARY KEY,
  degree_level VARCHAR(50),
  amount DECIMAL(10, 2),
  currency VARCHAR(10),
  fee_type VARCHAR(50) DEFAULT 'tuition',
  tuition_type VARCHAR(30) DEFAULT 'unknown',
  amount_min DECIMAL(10, 2),
  amount_max DECIMAL(10, 2),
  normalized_monthly_amount DECIMAL(10, 2),
  normalization_note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (degree_level, amount, currency, fee_type, tuition_type)
);

CREATE TABLE IF NOT EXISTS ${PROGRAM_TUITION_MAP_TABLE} (
  degree_program_id INTEGER NOT NULL REFERENCES ${DEGREE_PROGRAMS_TABLE}(id) ON DELETE CASCADE,
  tuition_pattern_id INTEGER NOT NULL REFERENCES ${TUITION_PATTERNS_TABLE}(id) ON DELETE CASCADE,
  PRIMARY KEY (degree_program_id, tuition_pattern_id)
);
